### ISSUE TITLE
FeiRuoTabplus BUG:搜索栏新标签并不能重用空白标签

### ISSUE THREAD

**Issue by kidzgy** [feiruo/userChromeJS#11]
设置搜索栏新标签打开的话，并不会重用空白标签，而书签地址栏其他的，倒是能重用空白标签。

FF42。

**Comment by feiruo** [comment]
新标签打开搜索是自带的功能
about:config
browser.search.openintab

**Comment by kidzgy** [comment]
新标签打开搜索虽然是自带的功能，可是立于原基础上，可是要重用空白标签不该就是扩展脚本当为之事吗？ 本来如果没有空白标签，就新开标签搜索；有空白标签自然应该重用标签页，否则新开个搜索还要关闭左边的空白标签不是很蛋疼吗
