### ISSUE TITLE
启用FeiRuoMouse后无法在在线视频里右键弹出菜单

### ISSUE THREAD

**Issue by xzhlksh** [feiruo/userChromeJS#24]
如题
我在斗鱼看直播的时候，想通过右键切换直播线路的时候，发现在视频里点击右键完全没有响应，用脚本管理器禁用FeiRuoMouse脚本后可以正常切换线路。
另外，“转到页尾”这个命令里必须把`goDoCommand("cmd_scrollBottom");`这局解除注释才能生效，测试环境为FF49.0b1

**Comment by feiruo** [comment]
视频右键问题已修复，关于E10S失效问题，可以看看配置文件里面相关命令，大多都有支持E10的方案，只是注释掉了而已。。
