### ISSUE TITLE
火狐48上FeiRuoTabplus更改标签滚轮事件

### ISSUE THREAD

**Issue by sakuyaa** [feiruo/userChromeJS#25]
火狐48上似乎改了标签滚轮事件，DOMMouseScroll不管用了，用wheel事件倒是可以
我就改了560行，DOMMouseScroll改成wheel；594和599行，detail改成deltaY，好像就可以了
[FeiRuoTabplus.uc.js.txt](https://github.com/feiruo/userChromeJS/files/407005/FeiRuoTabplus.uc.js.txt)
不知道这样有没有造成其他问题。。。

**Comment by feiruo** [comment]
已修复
