### ISSUE TITLE
启用FeiRuoNet.uc.js脚本这个网站就崩溃啊 怎么办？

### ISSUE THREAD

**Issue by nomosaic** [feiruo/userChromeJS#29]
这个网站
http://zxc7028ko.pixnet.net/blog/post/203346652-%E6%96%B0%E7%94%9F%E4%BB%A3%E9%AB%98%E5%9B%9E%E9%A0%AD%E7%8E%87%E5%A5%B3%E7%A5%9E%EF%BC%9Aplayback%E6%88%90%E5%93%A1%E5%80%8B%E4%BA%BA%E5%9F%BA%E6%9C%AC%E8%B3%87
![2016-08-21_103506](https://cloud.githubusercontent.com/assets/14254798/17834991/3f0d60b4-678b-11e6-8159-50b15889ba94.jpg)

**Comment by feiruo** [comment]
我这里没有问题，你看下设置是否有修改某些内容，或者直接删掉_FeiRuoNet.js这个文件试试

**Comment by feiruo** [comment]
监听连接状态的原因，某些网站开启E10S后有这个情况，目前已修复
