### ISSUE TITLE
showFlagS脚本切换UA功能有错误，导致百度盘下载速度过慢

### ISSUE THREAD

**Issue by lm789632** [feiruo/userChromeJS#3]
rt
http://tieba.baidu.com/p/3634650814

**Comment by Firef0x** [comment]
@lm789632 ，你好！

请自行修改 [_showFlagS.js 第 597 行](https://github.com/feiruo/userChromeJS/blob/master/showFlagS%2F_showFlagS.js#L597)，去掉 `"BaiduYunGuanJia "` 这个字符串最后的空格，或者使用已经修复的 [showFlagS 1.6.2.5 版本](https://github.com/dupontjoy/userChromeJS/blob/master/SubScript%2FshowFlagS.uc.js) 。

参考 [showFlagS显IP地址和国旗UC脚本 299 楼](http://bbs.kafan.cn/forum.php?mod=redirect&goto=findpost&ptid=1666483&pid=34534753)

---

### @feiruo 大大烦请及时推送最新的 `1.6.2.5` 版本到此仓库，谢谢！ GitHub 自动提醒服务比手动刷卡饭或者火狐饭更有效率。 :wink:

**Comment by feiruo** [comment]
感谢反馈，已修复，请更新脚本和配置文件。

**Comment by Firef0x** [comment]
大神真勤快，居然这几天大幅改进升到 `1.7.0.0` 了！必须 32 个 :+1: ！不过提交信息里的 `Final` 的意思不会是不再更新吧？ :scream:
