### ISSUE TITLE
用了Tabplus脚本会自动关闭标题栏。

### ISSUE THREAD

**Issue by Iy204** [feiruo/userChromeJS#32]
怎么打开？我比较喜欢标题栏。

**Comment by feiruo** [comment]
标题栏？是菜单栏？本脚本只针对标签的行为进行修改，并不会修改样式，你可以尝试禁用本脚本看看

**Comment by Iy204** [comment]
就是定制界面里面那个标题栏。是你的脚本问题，就是那个去除边框的。会把它变回默认那样。
