### ISSUE TITLE
bookmarkallmod.uc.js 的“保存在书签工具栏，否则保存在书签菜单”无效

### ISSUE THREAD

**Issue by XuQK** [feiruo/userChromeJS#4]
不管钩不勾选，都是保存在书签菜单，我想保存在书签工具栏来着。
还有排除列表不能在最后一行回车加行，只能在倒数第二行最后回车加行，算是个不算bug的bug吧。
Ubuntu 14.04，Firefox 37.0.1

**Comment by feiruo** [comment]
没有Ubuntu环境无法测试，不过Windows下没有你所述的问题，请更新到最新版本尝试，
如果还有问题，可以看看错误控制台是否有相关信息，如果有请贴给我看下，谢谢
