### ISSUE TITLE
FeiRuoTabPlus设置中标签、标签栏 事件里的项目移除或禁用无效

### ISSUE THREAD

**Issue by AlwaysWithYou** [feiruo/userChromeJS#5]
feiruo，你好！
我发现最新版的FeiRuoTabPlus.uc.js脚本在  脚本设置--标签、标签栏 事件  中添加的项目，即使点了移除按钮并看到该项被移除，该项却仍然生效，再次打开设置，会发现其又重新出现，在about:config中，userChromeJS.FeiRuoTabplus.Custom的值里也还是有该项目；若是将该项目禁用，虽然about:config中相应的值确实变成了0，但是该项仍然有效，不过再打开设置看，还是禁用的状态。
我目前在用32位的Firefox 37.0.1，系统是Win7 x64。已新建过配置测试，也是如此问题。

**Comment by feiruo** [comment]
你好，规则的启用禁用问题已经解决，更新即可。
另外并没有移除是我设定的机制，规则列表为空的时候此次保存不生效，就是不会把规则置空。
为的是“恢复默认”的时候，排除规则这一部分，这样幸苦制定的规则就不会因为重置一次就没有了。

**Comment by AlwaysWithYou** [comment]
感谢解答与修复！
