### ISSUE TITLE
FeiRuoTabplus使用问题，请老大留意

### ISSUE THREAD

**Issue by howbig** [feiruo/userChromeJS#7]
FF 38.0.1，UC-MIX环境，使用脚本有以下问题，应该不是个例：
1.书签用左键不能打开
2.用fireIE扩展打开IE内核标签时，在IE当前使用滚轮切换标签无效（同类扩展未测试）
3.撤销按钮图标的鼠标点击响应似乎写错了，左键单击还原刚刚关闭窗口成了右键还原（同时弹出下拉菜单），如果添加自定义图标功能请留意
另，建议图标颜色调整下，好像比FF默认主题的深

**Comment by feiruo** [comment]
1、已经修复了。
2、原因尚未清楚，等待修复。
3、没写错，是图标和下拉箭头分别不同的功能。
图标的话，我这里是统一的啊，根据不同主题可以自己修改的

**Comment by howbig** [comment]
问题2 可以考虑联系下原扩展作者，使用中问题不大，IETAB类其他扩展是否有这个问题未验证。
问题3 是这个意思：按照更新说明“修改撤销按钮机 制。左键弹出菜单，右键撤销，无法撤销则尝试恢复窗口”——现在实际使用的效果是：按钮的图标是分为“还原箭头”和“下拉菜单三角”两部分的，左键“箭头”没有任何反应，左键“三角”弹出撤销菜单，右键“箭头”或者“三角”撤销标签——跟说明里的效果差不多，不过建议参考下Undo Closed Tabs Button这个扩展的实现方式，也就是“箭头”和“三角”功能分开，左键箭头还原，左键三角显示菜单；如果功能还是用右键还原，左键菜单的话，也应该保证左键箭头可以显示菜单，不过这样的话箭头和三角功能就会完全重复，是不是可以取消掉三角了。

另外还有个问题，firefox工具栏上自带功能的 按钮（比如历史、收藏），下拉菜单的显示效果比较好，背景颜色跟随系统的圆角气泡，这种显示效果可以用js脚本实现吗？Undo Closed Tabs Button这个扩展是不行的，但是有个国产的扩展“火狐捷径”（就是谋智中国弄得那个中国版自带扩展）是可以这样显示的，老大可以考虑一下。

**Comment by howbig** [comment]
~~不好意思，之前没有更新脚本，刚刚看看了新脚本，右键还原取消了，现在是显示菜单，左键箭头还原、三角菜单，也就是问题三解决了
