### ISSUE TITLE
FeiRuoTabplus中设置新建标签在当前标签页右边的时候，会导致FIREFOX在重启后标签页顺序混乱

### ISSUE THREAD

**Issue by liangxyz** [feiruo/userChromeJS#9]
如题，设置新建标签在当前标签页右边的时候，会导致FIREFOX在重启后标签页顺序混乱，譬如：原本标签页的顺序是：1,2,3,4,5,但是关掉再打开之后，标签页的顺序却变成了：5,4,3,2,1。
版本0.52

**Comment by liangxyz** [comment]
楼主啊，新版依旧有这个问题，很头疼啊

**Comment by feiruo** [comment]
这个是Firefox自带的功能，脚本只是启用这个功能，并没有其他的操作，所以这个你可能需要直接去官方反馈
